### PR TITLE
Recreate/Adapt Fig 1--3 in indicators paper to hosp data, put in supplement

### PR DESCRIPTION
**Pull request by brookslogan**

### CODE REVIEW

**Comment by ryantibs** [comment]
Thanks @lcbrooks!  Overall looks quite good.  Some quick comments:  (Also tagging @mariajahja since she may know about the hospitalization signals in particular):

- Why does HSP-HOSP only start in ~Oct 2020?  Is that because you are using the "from claims only" signal?  Before that we had a different signal computed based on a mix of claims and EMR data (IIRC)?  Why isn't the "from claims only" signal available for earlier than Oct 2020, just due to the fact we started computing it then (no real lack of availability before)?
- Minor point, but I think we can use HSP-Hosp for the name/label, since HOSP is not an acronym.
- Figure S.10 shows nice corresponding overall.  But it's surprising in that there's actually not too much lead in the ascent of cases in picking up hospitalizations ... do we mention this at all?  I assume this is due to reporting delay in cases (much greater here than in hospitalizations, I would assume)?
- Figure S.11 shows strong correlations but a bit surprising that HSP-Hosp doesn't provide the strongest correlations to HHS hospitalizations.
- Given the last two points, and the fact that the strong correlations between reported cases and HHS hospitalizations is likely  helped by the excessive reporting delay in the former, I guess this begs the question: should we just omit CHNG-COVID and Cases from this analysis, and only show hospitalizations in Fig S.10 and Fig S.11?  I guess I'm leaning towards yes, otherwise a lot of additional explanation is warranted, which maybe is a distraction from the main point of comparison (reported hospitalizations, and claims-based hospitalizations).  Do you agree @capnrefsmmat?

**Comment by brookslogan** [comment]
> Why does HSP-HOSP only start in ~Oct 2020? Is that because you are using the "from claims only" signal? Before that we had a different signal computed based on a mix of claims and EMR data (IIRC)? Why isn't the "from claims only" signal available for earlier than Oct 2020, just due to the fact we started computing it then (no real lack of availability before)?

There may be an issue with the HHS and national aggregations: see this selection of the metadata:
```
                             signal geo_type   min_time   max_time
5  smoothed_adj_covid19_from_claims   county 2020-02-01 2021-06-17
6  smoothed_adj_covid19_from_claims      hhs 2020-10-04 2021-06-17
7  smoothed_adj_covid19_from_claims      hrr 2020-02-01 2021-06-17
8  smoothed_adj_covid19_from_claims      msa 2020-02-01 2021-06-17
9  smoothed_adj_covid19_from_claims   nation 2020-10-04 2021-06-17
10 smoothed_adj_covid19_from_claims    state 2020-02-01 2021-06-17
```
> Minor point, but I think we can use HSP-Hosp for the name/label, since HOSP is not an acronym.

Done locally; will batch up with other edits.

> Figure S.11 shows strong correlations but a bit surprising that HSP-Hosp doesn't provide the strongest correlations to HHS hospitalizations.

Thanks, took another look and spotted a bug; I don't think the correlations are calculated on the same set of instances for all signals.  Will see if this addresses this mismatch in expectations.

> Given the last two points, and the fact that the strong correlations between reported cases and HHS hospitalizations is likely helped by the excessive reporting delay in the former, I guess this begs the question: should we just omit CHNG-COVID and Cases from this analysis, and only show hospitalizations in Fig S.10 and Fig S.11? I guess I'm leaning towards yes, otherwise a lot of additional explanation is warranted, which maybe is a distraction from the main point of comparison (reported hospitalizations, and claims-based hospitalizations). Do you agree @capnrefsmmat?

This is possible (and what I did originally, but it looked a bit bare compared to the originals and added back some signals in case there was a particular point to be made), just let me know.

**Comment by ryantibs** [comment]
I have strong feelings but I think it's easier just to show HSP-Hosp and HHS-Hosp; then, less explanation will be required.  I'm not too worried about it being bare.  We can revisit this in the period between submission and revision, if we want to try to make the example richer.

**Comment by brookslogan** [comment]
Okay, I have fixed some things and limited the analysis to hospitalization signals only.  I don't know if I can calculate a national-level CHNG proportions from state-level ones, so I've just added an explanation rather than doing something to extend the signal's availability. Here's what the relevant pages look like now: 
[supplement-extract.pdf](https://github.com/cmu-delphi/covidcast-pnas/files/6689639/supplement-extract.pdf)

**Comment by brookslogan** [comment]
> Figure S.10 shows nice corresponding overall. But it's surprising in that there's actually not too much lead in the ascent of cases in picking up hospitalizations ... do we mention this at all? I assume this is due to reporting delay in cases (much greater here than in hospitalizations, I would assume)?

This may still need attention, although it doesn't make sense in this part of the supplement anymore.  Some notes:
- the reference date for cases is mostly the report date, sometimes by earlier dates --- depending on the definition of "reporting delay", this is 0 delay or potentially lots of delay
- the reference date for hospitalizations is date of admission
- if the reference date for cases were an earlier date related to testing, such as test date or specimen collection date, lead/lag relative to hospitalizations may be influenced by testing and reporting practices (severity-dependent testing, whether or not asymptomatic tests are included --- not sure if counties/states actually do this, age&location-dependent testing and disease patterns --- the "story" of testing supply & testing programs & the epidemic, ...)
- smoothing methods between cases and hospitalizations don't precisely match (boxcar vs. Gaussian + wday adjustment), but might "roughly" correspond to 7day windows

**Comment by capnrefsmmat** [comment]
Thanks; I'll merge for now (submission soon!) and then tweak as needed.

**Pull request merged**
